version: '3'

services:
  db:
    restart: always
    image: mongo:latest
    volumes:
      - "./mongodb:/data/db"
    env_file:
      - ./.env
    ports:
      - "27017-27019:27017-27019"

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/backend"
    entrypoint: "./deploy/entrypoints/entrypoint.sh"
    depends_on:
      - db
    ports:
      - "5000:5000"