"""empty message

Revision ID: 78796add66cf
Revises: 017e0191cfb7
Create Date: 2019-10-30 16:29:21.288034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78796add66cf'
down_revision = '017e0191cfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forecast', 'forecast_date', type_=sa.Date,
                    existing_type=sa.DateTime)
    op.create_unique_constraint('unique_forecast', 'forecast', ['city_id', 'forecast_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_forecast', 'forecast', type_='unique')
    op.alter_column('forecast', 'forecast_date', type_=sa.DateTime,
                    existing_type=sa.Date)
    # ### end Alembic commands ###
