"""empty message

Revision ID: 81c90942e1b8
Revises: 
Create Date: 2019-10-22 17:15:30.494023

"""
import json
import os

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer, String, Numeric


# revision identifiers, used by Alembic.

revision = '81c90942e1b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('main', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('temp', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('temp_min', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('temp_max', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('pressure', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sea_level', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('grnd_level', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('clouds', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_degrees', sa.Integer(), nullable=True),
    sa.Column('rain_mm', sa.Integer(), nullable=True),
    sa.Column('snow_mm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    data_upgrades()
    # ### end Alembic commands ###


def data_upgrades():
    city_fixture_path = os.path.join(os.environ['APPS_DIR'],
                                     'city/fixtures/cities.json')

    city_table = table('city',
                       column('id', Integer),
                       column('name', String),
                       column('country', String),
                       column('lon', Numeric),
                       column('lat', Numeric))

    with open(city_fixture_path) as fp:
        op.bulk_insert(city_table, json.load(fp))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast')
    op.drop_table('city')
    # ### end Alembic commands ###
